global:
  scrape_interval: "30s"
  evaluation_interval: 30s

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alert-manager.onrender.com

rule_files:
- "/rules/my_record_rules.yml"
- "/rules/my_alert_rules.yml"

scrape_configs:
- job_name: GO.Charity Auth microservice
  scrape_timeout: 25s
  static_configs:
  - targets:
    - "go-charity-auth-server.onrender.com"
  metrics_path: "/swagger-stats/metrics"
