global:
  scrape_interval: "30s"
scrape_configs:
- job_name: "GO.Charity Auth microservice"
  static_configs:
  - targets:
    - go-charity-auth-server.onrender.com
  metrics_path: /metrics

- job_name: "GO.Charity Auth microservice (swagger-stats)"
  static_configs:
  - targets:
    - "go-charity-auth-server.onrender.com"
  metrics_path: /swagger-stats/metrics
