on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build-deploy:
    name: Build and deploy to GKE Cluster
    runs-on: ubuntu-latest
    env:
      IMAGE: gocharity/prometheus
      GKE_CLUSTER: gocharity-cluster
      GKE_ZONE: us-central1
    steps:
      - name: Chackout
        uses: actions/checkout@v3

      - name: Authenticate Google CLI
        id: auth-google-cli
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GKE_SA_KEY }}

      - name: Authenticate for Docker Hub
        run: docker login -u ${{secrets.D_USER}} -p ${{secrets.D_PASS}}

      - name: Build Image
        run: docker build -t ${{env.IMAGE}}:latest -t ${{env.IMAGE}}:${{github.sha}} .

      - name: Publish Images to DockerHub repo
        run: |
          docker push ${{env.IMAGE}}:latest
          docker push ${{env.IMAGE}}:${{github.sha}}

      - name: Set up the GKE Cluster credentials
        uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Deploy app to Cluster as a deployment
        run: |
          kubectl apply -f kube-deploy.yml
          kubectl get pods
